### ISSUE TITLE
Need to fix the "supported" tests to match the changed Loop UI/behavior

### ISSUE THREAD

**Issue by stephendonner** [mozilla/hello-tests#12]
https://webqa-ci.mozilla.com/job/hello.prod.supported.saucelabs/534/ started failing, and I was told in #loop that there was a Loop UI change recently, and the tests need updating.

@Standard8 @dmose ^^^ (I can't find dcritch on GitHub, sorry).

**Comment by dmose** [comment]
CC @daveccrit

**Comment by davehunt** [comment]
See https://github.com/mozilla/hello-tests/pull/13
