### ISSUE TITLE
When should we end-of-life this repo/test coverage, given the impending shutdown of Firefox Hello?

### ISSUE THREAD

**Issue by stephendonner** [mozilla/hello-tests#29]
Given https://support.mozilla.org/en-US/kb/hello-status and the pronouncement that Firefox Hello will be shutting down effective September 13, 2016, what should happen with this current set of tests?

/cc @Standard8 + cc/ @mozilla/web-qa-sorcerers

**Comment by davehunt** [comment]
I would suggest we just let them run until the service is shutdown, and at that point [deactivate the repository](https://wiki.mozilla.org/QA/Execution/Web_Testing/Repositories#Deactivating_a_repository).

**Comment by Standard8** [comment]
I haven't quite decided when we should shut these down yet, sometime around 13 Sept is probably a good target date. I've got this on my list of things to remember to close out.

**Comment by stephendonner** [comment]
Sounds good, @davehunt + @Standard8
